### ISSUE TITLE
Multiplayer Mode does not work correctly

### ISSUE THREAD

**Issue by ghost** [CarlssonK/Blackjack-Game-Multiplayer#1]
The Multiplayer Mode sadly does not work correctly. When I send my friends the link for them to join the room I created it initially works but then it buggs out. When they click on the link they get forwarded to my server where I have installed "Blackjack-Game-Multiplayer" then they enter their name and click on "Join-Room" now four things can happen when they click on that button!
1. Nothing!
2. The page reloads itself and the "join room" button becomes a "create room" button
3. They join but the room they join is not my room in this room they will be able to sit but they won't be able to place bets although the chip select phase is working. When they join this buggy room the URL bar won't display any 6-digit room-code!
4. They join the room and the room-code does appear in the URL-bar but they won't show up at the "users in room" section" nor at the place, they selected to sit at. In their perspective the "users in room" section is completely empty not even themselves are listed there (this applies to point 3 as well)

I don't know what causes this issue but I would be happy if this would be fixed or if somebody from the dev-teams would show me what has gone wrong with my installation.
I would happily provide log files (if they exist) for the dev-teams to analyze if I would be told where I can find those!

**Picture from the view of someone who has joined a hosted session (description under the picture)**
![Screenshot_2021-02-09 PLAY BLACKJACK WITH YOUR FRIENDS](https://user-images.githubusercontent.com/78815647/107406448-bf666000-6b08-11eb-8664-410b24f0e008.png)
I decided to add a picture to show what this bugged lobby looks like so everybody can get a clear picture.
As you can see I joined a room that my friend created the link had this format "http://[domain]/GI6647" I entered my name as "Player" and clicked "join-room". I was placed in a room and the URL-bar did show the same room-code as my friend. I sat down at one of the slots and selected a bet 1500 normally I would need to confirm this by clicking on the "place-bet" button but this does not show up here! My friend the host who is seated on the first slot shows neither in the "users in room" section nor at the place where he is seated. He too cannot confirm his bet. Currently, only the play offline mode works reliably without any issue!

With regards!

sigbrecht

**Comment by carlssonk** [comment]
Hello there,

This seems to be because you have set up and hosting the game on your own
domain, is there any reasoning for that?

The code is currently set up so the game only works on
https://blackjack-multiplayer.herokuapp.com

I could make it support other domains than the one I have, but right now
you can go to the link above if you want to play with your friends.

Den tis 9 feb. 2021 19:13sigbrecht <notifications@github.com> skrev:

**Comment by ghost** [comment]
Well, I would be happy if you could make the appropriate changes so the game works fully on all hosted versions.
I was not aware that the online-mode would not work on my own hardware/domain. The readme did not mention this.
In addition, the "blackjack21.io" link in the readme file was and is broken, which I assumed was the preview to test the game and its capabilities.
So I thought to myself that the only option for me to play it with my friends was to host the game myself.
And with clear installation instructions, everything went quite smooth and nice.
I like hosting my own stuff if I have the chance to do it as I do with Nextcloud or Mumble.
I would be very grateful if you could release an update so I can play with my friends on our own server.
Privacy is very important to me and my friends! If you would make this change your version of online blackjack available on GitHub would be truly the best version I tested so far!

With regards!

sigbrecht

**Comment by carlssonk** [comment]
Ok I see. You could actually just change 1 line in the code to make it work
on your own server.

Inside "index.js" on line 73 you will see the url "
https://blackjack-multiplayer.herokuapp.com/", change this to your own
domain, don't forget "/" at the end.
[image: url_link.jpg]

Let me know if you have any problems.

Note that this app is quite buggy, etc. there are some bugs where your
balance will increase when a player joins your room or sometimes the cards
won't show up when you've placed a bet. This is stuff I won't fix, other
than that the game works like it should.

**Comment by nxtlvl2t8k** [comment]
Hi Carlsson,  We would like permission to use your BlackJack Code.

**Comment by carlssonk** [comment]
> Hi Carlsson, We would like permission to use your BlackJack Code.

The code is free to use :)
