### ISSUE TITLE
Critical business logic on client side

### ISSUE THREAD

**Issue by nicksterious** [CarlssonK/Blackjack-Game-Multiplayer#4]
I'm looking at your code (awesome work, congratulations!) and it appears some of the game logic works on the client side?

Eg removing/adding to players' balance, deciding whether a hand was won/lost...

Basically this means any script kiddie with like 3 seconds of javascript knowledge can win any game and any amount.

Is there a way all this logic can be moved to the server side?

Cheers!
N

**Comment by carlssonk** [comment]
Yo!

Yeah each client essentially has its own game state/logic which is obviously wrong from a security standpoint. The code is not maintained anymore as it was just a pet project of mine so it would be better and easier to rewrite the code completely :)
