### ISSUE TITLE
Double Aces Issue

### ISSUE THREAD

**Issue by lrutjens** [CarlssonK/Blackjack-Game-Multiplayer#6]
![image](https://github.com/carlssonk/Blackjack-Game-Multiplayer/assets/93109413/4df2bcea-ca52-402d-9775-7718e0aedf0e)
double aces are bugged, i drew a 10 afterwards then my turn immediately ended

**Comment by carlssonk** [comment]
Weird, this never happened to me before. 2 aces should give 21.

The code is poorly made and not maintained anymore as it's a pet project.

(Will close but open to PRs if anyone dares to jump into the code and fix it :))
